[package]
name = "helium-wsl-macros"
version = "0.2.0"
edition = "2024"
description = "Proc macros for the helium-wsl library"
license = "MIT"
repository = "https://github.com/xZepyx/helium"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
