/// Errors that can occur when loading or parsing configuration.
#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    /// The config file could not be read.
    #[error("failed to read config: {0}")]
    Io(#[from] std::io::Error),
    /// The config file could not be parsed as JSON.
    #[error("failed to parse config: {0}")]
    Parse(#[from] serde_json::Error),
}

impl ConfigError {
    /// Wrap an io::Error as a reading error.
    pub fn reading(e: std::io::Error) -> Self {
        ConfigError::Io(e)
    }

    /// Wrap a serde_json::Error as a parsing error.
    pub fn parsing(e: serde_json::Error) -> Self {
        ConfigError::Parse(e)
    }
}

// Re-export what the proc macro generates.
// The proc macro generates types with the name given in the macro invocation
// (typically `Config`), so we expose a type alias.
//
// By default the macro generates a struct named `Config` – this module aliases
// it as `HeliumConfig` for clarity, but users who `use helium::config::Config`
// get it directly.
/// The root config type generated by [`helium_config!`](crate::helium_config).
///
/// You typically use this via the `helium_config!` macro and access fields
/// directly. The type is re-exported as [`HeliumConfig`] for convenience.
#[doc(inline)]
pub use helium_macros::*;
